#!/bin/sh

# check if gum is installed
if ! command -v gum &> /dev/null
then
    echo "gum is not installed. Please install gum first."
    exit
fi

GUM_SPIN_SHOW_OUTPUT=true # buggy for some reason

tools="asdf brew cargo gh go rustup"
available_tools=""

# check which tools are available
for tool in $tools; do
    if type $tool &> /dev/null; then
        available_tools="$available_tools $tool"
    fi
done

choices=""

# check which tools are installed
for tool in $available_tools; do
    if command -v $tool &> /dev/null; then
        choices="$choices $tool"
    fi
done

# add --all option
if [ "$1" != "--all" ]; then
    echo "Choose what packages you want to update: "
    choices=$(gum choose $choices --no-limit)
else
    choices=$available_tools
fi

for choice in $choices; do
    if [ "$choice" = "asdf" ]; then
        echo "Updating asdf plugins..."
        cmd="asdf plugin update --all"
        gum spin -s minidot --title "Running '$cmd'" -- $cmd
    elif [ "$choice" = "rustup" ]; then
        echo "Updating Rust toolchain..."
        cmd="rustup update"
        gum spin -s minidot --title "Running '$cmd'" -- $cmd
    elif [ "$choice" = "cargo" ]; then
        echo "Updating Rust binaries..."
        cmd="cargo install-update -a"
        gum spin -s minidot --title "Running '$cmd'" -- $cmd
    elif [ "$choice" = "go" ]; then
        if ! command -v go-global-update &> /dev/null; then
            cmd="go install github.com/valyala/go-global-update@latest"
            gum spin -s minidot --title "Installing go-global-update..." -- $cmd
        fi
        echo "Updating Go binaries..."
        cmd="go-global-update"
        gum spin -s minidot --title "Running '$cmd'" -- $cmd
    elif [ "$choice" = "brew" ]; then
        echo "Updating brew..."
        brew update
        brew upgrade
        brew upgrade `brew list --cask`
        brew cleanup
        brew autoremove 
        brew doctor
    elif [ "$choice" = "gh" ]; then
        echo "Updating gh extensions..."
        cmd="gh extension upgrade --all"
        gum spin -s minidot --title "Running '$cmd'" -- $cmd
    fi
done
echo "Done!"
